name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your_dockerhub_username/react-app:latest .
        docker push your_dockerhub_username/react-app:latest

    - name: SSH to DigitalOcean and update container
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.DO_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull your_dockerhub_username/react-app:latest
          docker-compose -f /path/to/docker-compose.yml up -d frontend
